<a href="https://colab.research.google.com/github/emnjunior/tutorials/blob/master/Untitled6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install -q kaggle

In [2]:
!mkdir -p ~/.kaggle

In [3]:
!cp kaggle.json ~/.kaggle

In [8]:
!chmod 600 ~/.kaggle/kaggle.json

In [12]:
import os
os.environ['KAGGLE_USERNAME'] = "edsonmendesjunior" # username from the json file
os.environ['KAGGLE_KEY'] = "eabc26f6b1cb2e3f86e8a1e788d43077" # key from the json file
!kaggle competitions download -c ieee-fraud-detection

Warning: Looks like you're using an outdated API Version, please consider updating (server 1.5.10 / client 1.5.4)
Downloading sample_submission.csv.zip to /content
  0% 0.00/1.14M [00:00<?, ?B/s]
100% 1.14M/1.14M [00:00<00:00, 36.7MB/s]
Downloading train_transaction.csv.zip to /content
 70% 41.0M/58.3M [00:01<00:00, 25.5MB/s]
100% 58.3M/58.3M [00:01<00:00, 43.1MB/s]
Downloading test_transaction.csv.zip to /content
 90% 47.0M/52.2M [00:01<00:00, 31.5MB/s]
100% 52.2M/52.2M [00:01<00:00, 39.9MB/s]
Downloading train_identity.csv.zip to /content
  0% 0.00/3.26M [00:00<?, ?B/s]
100% 3.26M/3.26M [00:00<00:00, 218MB/s]
Downloading test_identity.csv.zip to /content
  0% 0.00/3.21M [00:00<?, ?B/s]
100% 3.21M/3.21M [00:00<00:00, 105MB/s]

In [14]:
!mkdir data
!unzip "/content/train_transaction.csv.zip" -d data
!unzip "/content/train_identity.csv.zip" -d data

mkdir: cannot create directory ‘data’: File exists
Archive:  /content/train_transaction.csv.zip
replace data/train_transaction.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: r
new name: Archive:  /content/train_identity.csv.zip
  inflating: data/train_identity.csv

In [15]:
import pandas as pd

df_transaction_train = pd.read_csv("/content/data/train_transaction.csv")
df_transaction_train.head()

   TransactionID  isFraud  TransactionDT  ...  V337 V338  V339
0        2987000        0          86400  ...   NaN  NaN   NaN
1        2987001        0          86401  ...   NaN  NaN   NaN
2        2987002        0          86469  ...   NaN  NaN   NaN
3        2987003        0          86499  ...   NaN  NaN   NaN
4        2987004        0          86506  ...   0.0  0.0   0.0

[5 rows x 394 columns]